using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace YayaInk.Orleans.Unions.Generators;

/// <summary>
/// Scans every type marked with <c>[YayaInk.Orleans.Unions.GenerateUnionSerializerAttribute]</c>
/// and emits an Orleans <c>IFieldCodec&lt;TUnion&gt;</c> / <c>IDeepCopier&lt;TUnion&gt;</c>
/// pair for it, decorated with <c>[RegisterSerializer]</c> / <c>[RegisterCopier]</c>.
/// It also emits an assembly-level <c>TypeManifestProvider</c> so that
/// <c>services.AddSerializer(b =&gt; b.AddAssembly(...))</c> can discover the generated
/// codecs/copiers — the registration attributes alone are not sufficient.
///
/// Generic unions (e.g. <c>Result&lt;T&gt;</c>) emit a generic codec/copier of the same
/// arity; the manifest registers the open generic so Orleans constructs the closed
/// instance on demand. Nested unions (a union as a case payload) are supported because
/// the generated codec only needs <c>IFieldCodec&lt;TCase&gt;</c> for each case type.
///
/// <para>
/// <b>Compiler-shape note.</b>
/// Per the C# 15 spec, the <c>union</c> keyword always lowers to a struct
/// wrapper with a single <c>object? Value</c> field, regardless of the case
/// types or generic constraints. <c>where T : struct</c> does <i>not</i>
/// switch the lowering to a tagged / typed-fields layout — that non-boxing
/// form is an opt-in pattern (<c>HasValue</c> + <c>bool TryGetValue(out T)</c>
/// overloads) reserved for <i>hand-written</i> <c>[Union] struct</c> types,
/// not something the compiler ever auto-emits for a <c>union</c> declaration.
/// This generator therefore dispatches via <c>((IUnion)value).Value</c>,
/// which matches the only shape <c>union</c> declarations produce. The only
/// boxing on the value-case path is the one the union's own constructor
/// performs; the serializer adds none on top of that.
/// <c>CompilerShapeProbeTests</c> pins this lowering as a stability guard:
/// if Roslyn ever changes the lowering of <c>union</c> declarations, that
/// probe trips and the dispatch model here needs to be revisited.
/// </para>
/// </summary>
[Generator]
public sealed class UnionSerializerGenerator : IIncrementalGenerator
{
    private const string MarkerAttributeFullName = "YayaInk.Orleans.Unions.GenerateUnionSerializerAttribute";
    private const string GeneratedNamespace = "YayaInk.Orleans.Unions.Generated";

    private static readonly DiagnosticDescriptor UnionNoCases = new(
        id: "YIOU002",
        title: "Union has no public single-parameter constructors",
        messageFormat: "Union '{0}' has no public single-parameter constructors; nothing to generate",
        category: "YayaInkOrleansUnions",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var unions = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MarkerAttributeFullName,
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,
                transform: static (ctx, _) => Extract(ctx))
            .Where(static u => u is not null)
            .Select(static (u, _) => u!);

        context.RegisterSourceOutput(unions, static (spc, model) =>
        {
            foreach (var diag in model.Diagnostics)
                spc.ReportDiagnostic(diag);

            if (!model.CanEmit)
                return;

            var (hintName, source) = Emit(model);
            spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        });

        var collected = unions.Where(static u => u.CanEmit).Collect();
        context.RegisterSourceOutput(collected, static (spc, models) =>
        {
            if (models.IsDefaultOrEmpty) return;
            var (hint, src) = EmitManifest(models);
            spc.AddSource(hint, SourceText.From(src, Encoding.UTF8));
        });
    }

    private static (string HintName, string Source) EmitManifest(ImmutableArray<UnionModel> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine();
        sb.Append("[assembly: global::Orleans.Serialization.Configuration.TypeManifestProvider(typeof(global::")
          .Append(GeneratedNamespace).AppendLine(".UnionMetadataProvider))]");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("public sealed class UnionMetadataProvider : global::Orleans.Serialization.Configuration.TypeManifestProviderBase");
        sb.AppendLine("{");
        sb.AppendLine("    protected override void ConfigureInner(global::Orleans.Serialization.Configuration.TypeManifestOptions config)");
        sb.AppendLine("    {");
        foreach (var m in models)
        {
            var ns = m.Namespace is null ? string.Empty : m.Namespace + ".";
            var openArity = m.TypeParameters.Count == 0
                ? string.Empty
                : "<" + new string(',', m.TypeParameters.Count - 1) + ">";
            var codecFq = "global::" + ns + m.TypeName + "OrleansCodec" + openArity;
            var copierFq = "global::" + ns + m.TypeName + "OrleansCopier" + openArity;
            sb.Append("        config.Serializers.Add(typeof(").Append(codecFq).AppendLine("));");
            sb.Append("        config.Copiers.Add(typeof(").Append(copierFq).AppendLine("));");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return (GeneratedNamespace + ".UnionMetadataProvider.g.cs", sb.ToString());
    }

    private static UnionModel? Extract(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type)
            return null;

        var diagnostics = new List<Diagnostic>();
        var location = type.Locations.FirstOrDefault() ?? Location.None;
        var canEmit = true;

        var typeParameters = type.TypeParameters
            .Select(tp => tp.Name)
            .ToList();

        var typeParameterConstraints = type.TypeParameters
            .Select(BuildConstraintClause)
            .Where(s => s.Length > 0)
            .ToList();

        var cases = new List<CaseModel>();
        int tag = 1;
        foreach (var ctor in type.InstanceConstructors)
        {
            if (ctor.DeclaredAccessibility != Accessibility.Public) continue;
            if (ctor.Parameters.Length != 1) continue;
            var p = ctor.Parameters[0];
            cases.Add(new CaseModel(
                tag: tag,
                typeFullyQualified: p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                shortIdentifier: "Case" + tag));
            tag++;
        }

        if (cases.Count == 0)
        {
            diagnostics.Add(Diagnostic.Create(UnionNoCases, location, type.ToDisplayString()));
            canEmit = false;
        }

        return new UnionModel(
            ns: type.ContainingNamespace.IsGlobalNamespace
                ? null
                : type.ContainingNamespace.ToDisplayString(),
            typeName: type.Name,
            typeParameters: typeParameters,
            typeParameterConstraints: typeParameterConstraints,
            unionFullyQualified: type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            cases: cases,
            canEmit: canEmit,
            diagnostics: diagnostics);
    }

    private static string BuildConstraintClause(ITypeParameterSymbol tp)
    {
        var parts = new List<string>();
        if (tp.HasReferenceTypeConstraint)
            parts.Add(tp.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
        if (tp.HasValueTypeConstraint) parts.Add("struct");
        if (tp.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
        if (tp.HasNotNullConstraint) parts.Add("notnull");
        foreach (var ct in tp.ConstraintTypes)
            parts.Add(ct.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        if (tp.HasConstructorConstraint) parts.Add("new()");
        if (parts.Count == 0) return string.Empty;
        return "where " + tp.Name + " : " + string.Join(", ", parts);
    }

    private static (string HintName, string Source) Emit(UnionModel m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using global::Orleans;");
        sb.AppendLine("using global::Orleans.Serialization.Buffers;");
        sb.AppendLine("using global::Orleans.Serialization.Cloning;");
        sb.AppendLine("using global::Orleans.Serialization.Codecs;");
        sb.AppendLine("using global::Orleans.Serialization.GeneratedCodeHelpers;");
        sb.AppendLine("using global::Orleans.Serialization.Serializers;");
        sb.AppendLine("using global::Orleans.Serialization.WireProtocol;");
        sb.AppendLine();

        if (m.Namespace is not null)
        {
            sb.Append("namespace ").Append(m.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        var unionT = m.UnionFullyQualified;
        var tparamList = m.TypeParameters.Count == 0
            ? string.Empty
            : "<" + string.Join(", ", m.TypeParameters) + ">";
        var codecName = m.TypeName + "OrleansCodec" + tparamList;
        var copierName = m.TypeName + "OrleansCopier" + tparamList;
        var codecCtorName = m.TypeName + "OrleansCodec";
        var copierCtorName = m.TypeName + "OrleansCopier";
        var constraints = m.TypeParameterConstraints.Count == 0
            ? string.Empty
            : " " + string.Join(" ", m.TypeParameterConstraints);

        // ---------- Codec ----------
        sb.AppendLine("[global::Orleans.RegisterSerializer]");
        sb.Append("public sealed class ").Append(codecName)
          .Append(" : global::Orleans.Serialization.Codecs.IFieldCodec<").Append(unionT).Append(">")
          .AppendLine(constraints);
        sb.AppendLine("{");
        sb.Append("    private readonly global::System.Type _codecFieldType = typeof(").Append(unionT).AppendLine(");");
        foreach (var c in m.Cases)
        {
            sb.Append("    private readonly global::Orleans.Serialization.Codecs.IFieldCodec<")
              .Append(c.TypeFullyQualified).Append("> _codec_").Append(c.Tag).AppendLine(";");
        }
        sb.AppendLine();
        sb.Append("    public ").Append(codecCtorName).AppendLine("(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider)");
        sb.AppendLine("    {");
        foreach (var c in m.Cases)
        {
            sb.Append("        _codec_").Append(c.Tag)
              .Append(" = global::Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Codecs.IFieldCodec<")
              .Append(c.TypeFullyQualified).AppendLine(">>(this, codecProvider);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // WriteField
        sb.Append("    public void WriteField<TBufferWriter>(scoped ref global::Orleans.Serialization.Buffers.Writer<TBufferWriter> writer, uint fieldIdDelta, global::System.Type expectedType, ")
          .Append(unionT).AppendLine(" value)")
          .AppendLine("        where TBufferWriter : global::System.Buffers.IBufferWriter<byte>")
          .AppendLine("    {")
          .AppendLine("        writer.WriteFieldHeader(fieldIdDelta, expectedType, _codecFieldType, global::Orleans.Serialization.WireProtocol.WireType.TagDelimited);")
          // The reader side calls ReferenceCodec.MarkValueField(reader.Session) for this
          // field so its per-session reference id counter advances. The writer side MUST
          // mirror that, otherwise the two counters drift and any reference-typed payload
          // that appears more than once in the same root graph (e.g. the same RefA shared
          // across two list elements) deserializes as ReferenceNotFoundException.
          .AppendLine("        global::Orleans.Serialization.Codecs.ReferenceCodec.MarkValueField(writer.Session);")
          .AppendLine("        var inner = ((global::System.Runtime.CompilerServices.IUnion)value).Value;")
          .AppendLine("        switch (inner)")
          .AppendLine("        {");
        foreach (var c in m.Cases)
        {
            sb.Append("            case ").Append(c.TypeFullyQualified).Append(" v_").Append(c.Tag).AppendLine(":")
              .Append("                global::Orleans.Serialization.Codecs.ByteCodec.WriteField(ref writer, 0, typeof(byte), (byte)").Append(c.Tag).AppendLine(", typeof(byte));")
              .Append("                _codec_").Append(c.Tag).Append(".WriteField(ref writer, 1, typeof(").Append(c.TypeFullyQualified).Append("), v_").Append(c.Tag).AppendLine(");")
              .AppendLine("                break;");
        }
        sb.AppendLine("            default:")
          .AppendLine("                global::Orleans.Serialization.Codecs.ByteCodec.WriteField(ref writer, 0, typeof(byte), (byte)0, typeof(byte));")
          .AppendLine("                break;")
          .AppendLine("        }")
          .AppendLine("        writer.WriteEndObject();")
          .AppendLine("    }")
          .AppendLine();

        // ReadValue
        sb.Append("    public ").Append(unionT).AppendLine(" ReadValue<TInput>(scoped ref global::Orleans.Serialization.Buffers.Reader<TInput> reader, global::Orleans.Serialization.WireProtocol.Field field)")
          .AppendLine("    {")
          .AppendLine("        if (field.WireType == global::Orleans.Serialization.WireProtocol.WireType.Reference)")
          .Append("            return global::Orleans.Serialization.Codecs.ReferenceCodec.ReadReference<").Append(unionT).AppendLine(", TInput>(ref reader, field);")
          .AppendLine("        field.EnsureWireTypeTagDelimited();")
          .AppendLine("        global::Orleans.Serialization.Codecs.ReferenceCodec.MarkValueField(reader.Session);")
          .AppendLine("        byte tag = 0;")
          .Append("        ").Append(unionT).AppendLine(" result = default;")
          .AppendLine("        uint fieldId = 0;")
          .AppendLine("        while (true)")
          .AppendLine("        {")
          .AppendLine("            var header = reader.ReadFieldHeader();")
          .AppendLine("            if (header.IsEndBaseOrEndObject) break;")
          .AppendLine("            fieldId += header.FieldIdDelta;")
          .AppendLine("            switch (fieldId)")
          .AppendLine("            {")
          .AppendLine("                case 0:")
          .AppendLine("                    tag = global::Orleans.Serialization.Codecs.ByteCodec.ReadValue(ref reader, header);")
          .AppendLine("                    break;")
          .AppendLine("                case 1:")
          .AppendLine("                    switch (tag)")
          .AppendLine("                    {");
        foreach (var c in m.Cases)
        {
            sb.Append("                        case ").Append(c.Tag).AppendLine(":")
              .Append("                            result = new ").Append(unionT).Append("(_codec_").Append(c.Tag).AppendLine(".ReadValue(ref reader, header));")
              .AppendLine("                            break;");
        }
        sb.AppendLine("                        default:")
          .AppendLine("                            reader.ConsumeUnknownField(header);")
          .AppendLine("                            break;")
          .AppendLine("                    }")
          .AppendLine("                    break;")
          .AppendLine("                default:")
          .AppendLine("                    reader.ConsumeUnknownField(header);")
          .AppendLine("                    break;")
          .AppendLine("            }")
          .AppendLine("        }")
          .AppendLine("        return result;")
          .AppendLine("    }")
          .AppendLine("}")
          .AppendLine();

        // ---------- Copier ----------
        sb.AppendLine("[global::Orleans.RegisterCopier]");
        sb.Append("public sealed class ").Append(copierName)
          .Append(" : global::Orleans.Serialization.Cloning.IDeepCopier<").Append(unionT).Append(">")
          .AppendLine(constraints);
        sb.AppendLine("{");
        foreach (var c in m.Cases)
        {
            sb.Append("    private readonly global::Orleans.Serialization.Cloning.IDeepCopier<")
              .Append(c.TypeFullyQualified).Append("> _copier_").Append(c.Tag).AppendLine(";");
        }
        sb.AppendLine();
        sb.Append("    public ").Append(copierCtorName).AppendLine("(global::Orleans.Serialization.Serializers.ICodecProvider codecProvider)");
        sb.AppendLine("    {");
        foreach (var c in m.Cases)
        {
            sb.Append("        _copier_").Append(c.Tag)
              .Append(" = global::Orleans.Serialization.GeneratedCodeHelpers.OrleansGeneratedCodeHelper.GetService<global::Orleans.Serialization.Cloning.IDeepCopier<")
              .Append(c.TypeFullyQualified).AppendLine(">>(this, codecProvider);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    public ").Append(unionT).Append(" DeepCopy(").Append(unionT).AppendLine(" input, global::Orleans.Serialization.Cloning.CopyContext context)");
        sb.AppendLine("    {");
        sb.AppendLine("        var inner = ((global::System.Runtime.CompilerServices.IUnion)input).Value;");
        sb.AppendLine("        switch (inner)");
        sb.AppendLine("        {");
        foreach (var c in m.Cases)
        {
            sb.Append("            case ").Append(c.TypeFullyQualified).Append(" v_").Append(c.Tag).AppendLine(":")
              .Append("                return new ").Append(unionT)
              .Append("(_copier_").Append(c.Tag)
              .Append(".DeepCopy(v_").Append(c.Tag).AppendLine(", context));");
        }
        sb.AppendLine("            default:")
          .AppendLine("                return default;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var hint = (m.Namespace is null ? string.Empty : m.Namespace + ".")
                   + m.TypeName
                   + (m.TypeParameters.Count == 0 ? string.Empty : "_" + m.TypeParameters.Count)
                   + ".UnionOrleansSerializer.g.cs";

        return (hint, sb.ToString());
    }

    private sealed class UnionModel
    {
        public string? Namespace { get; }
        public string TypeName { get; }
        public List<string> TypeParameters { get; }
        public List<string> TypeParameterConstraints { get; }
        public string UnionFullyQualified { get; }
        public List<CaseModel> Cases { get; }
        public bool CanEmit { get; }
        public List<Diagnostic> Diagnostics { get; }

        public UnionModel(string? ns, string typeName, List<string> typeParameters,
            List<string> typeParameterConstraints,
            string unionFullyQualified, List<CaseModel> cases, bool canEmit,
            List<Diagnostic> diagnostics)
        {
            Namespace = ns;
            TypeName = typeName;
            TypeParameters = typeParameters;
            TypeParameterConstraints = typeParameterConstraints;
            UnionFullyQualified = unionFullyQualified;
            Cases = cases;
            CanEmit = canEmit;
            Diagnostics = diagnostics;
        }
    }

    private sealed class CaseModel
    {
        public int Tag { get; }
        public string TypeFullyQualified { get; }
        public string ShortIdentifier { get; }

        public CaseModel(int tag, string typeFullyQualified, string shortIdentifier)
        {
            Tag = tag;
            TypeFullyQualified = typeFullyQualified;
            ShortIdentifier = shortIdentifier;
        }
    }
}
